In [9]:
import pandas as pd
arquivo = pd.read_csv(r'C:\Users\HKC_H\OneDrive - pluus20\HKC\data-analytics\Learn\machineLearningProjectWine\wine_dataset.csv')
arquivo

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [10]:
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [12]:
arquivo['style'] = arquivo['style'].replace('red', 0)

In [13]:
arquivo['style'] = arquivo['style'].replace('white', 1)

In [15]:
arquivo

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [16]:
# Separando as variáveis entre preditoras e variável alvo.

y = arquivo['style'] # Selecionei a variável alvo
x = arquivo.drop('style', axis = 1) # Declarei todas as variáveis preditoras e tirei a coluna style com o comando drop

In [19]:
# Função de treino

from sklearn.model_selection import train_test_split

# Criando os conjuntos de dados de treino e teste

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3) 

# o 0.3 means that we want just 30% of the date for tests e the anpther 70% will be for training
# Da função a direita irá retornar 4 saídas que estão a esquerda

In [22]:
from sklearn.ensemble import ExtraTreesClassifier
#Criação do modelo

modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#Imprimindo resultados

resultado = modelo.score(x_teste, y_teste)

# Para x é passado os valores preditores e com esses dados ele vai tentar prever o resultado
# E comparar com o y_teste se ele acertou ou não com isso calculando a accuracy
print("Acurácia:", resultado)

Acurácia: 0.9953846153846154

In [27]:
x_teste

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
4702,7.0,0.250,0.45,2.3,0.045,40.0,118.0,0.99064,3.16,0.48,11.90,7
505,10.2,0.490,0.63,2.9,0.072,10.0,26.0,0.99680,3.16,0.78,12.50,7
3327,6.8,0.300,0.24,6.6,0.123,35.0,116.0,0.99530,3.07,0.48,9.40,5
103,8.1,0.575,0.22,2.1,0.077,12.0,65.0,0.99670,3.29,0.51,9.20,5
6465,5.7,0.410,0.21,1.9,0.048,30.0,112.0,0.99138,3.29,0.55,11.20,6
...,...,...,...,...,...,...,...,...,...,...,...,...
6332,5.2,0.185,0.22,1.0,0.030,47.0,123.0,0.99218,3.55,0.44,10.15,6
4443,8.0,0.220,0.31,5.6,0.049,24.0,97.0,0.99300,3.10,0.42,10.90,5
4439,6.5,0.370,0.33,3.5,0.036,23.0,92.0,0.99136,3.18,0.38,11.20,6
5791,6.7,0.200,0.24,6.5,0.044,28.0,100.0,0.99348,3.12,0.33,10.20,6
4591,6.6,0.200,0.27,10.9,0.038,29.0,130.0,0.99496,3.11,0.44,10.50,7

In [29]:
y_teste[400:403]

279     0
3862    1
2788    1
Name: style, dtype: int64

In [31]:
previsoes = modelo.predict(x_teste[400:403])
previsoes

# Comparando com os valores do In [29] Podemos ver que ele acertou as três

array([0, 1, 1], dtype=int64)